// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: writes.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
insert into users (handle, tx_hash)
values ($1, $2)
`

type CreateUserParams struct {
	Handle string
	TxHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Handle, arg.TxHash)
	return err
}
