// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: writes.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
insert into users (id, handle, bio, tx_hash)
values ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID     string
	Handle string
	Bio    string
	TxHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.Bio,
		arg.TxHash,
	)
	return err
}
